Added the dev script setup
dls-controls/tickit-devices pull request #30
Opened 2022-12-20 11:00 UTC by evalott100

Fixes #29

@DominicOram I added the dev environment script, This comes with a few warnings (e.g it wants a pyproject.toml and Distutils is imported before setup tools). Code tests pass, and tickit devices run fine. Idk if you want to fix the warnings here or make it a separate PR?

2022-12-20 16:40 UTC, DominicOram requested changes
This looks good, can we:
* Add the pre-commit yaml as in https://github.com/dls-controls/tickit-devices/pull/24/files?
* Install the hooks in the dev_env script
* Update the README

2022-12-20 16:40 UTC, DominicOram commented on .github/workflows/code.yml
> +    - cron: "0 8 * * WED"
Should: This comment disagrees with the cron job

2023-02-20 21:41 UTC, abbiemery commented
@evalott100 This may be solved now by #32

2023-02-21 08:40 UTC, evalott100 commented
@abbiemery Yep, all it would be adding is the .sh to do the pip venv installation which I think is unnecessary anyway. Closing.

2023-02-21 08:40 UTC, closed without merging